### ISSUE TITLE
Add to Galaxy

### ISSUE THREAD

**Issue by spech66** [tag1consulting/borgbackup#9]
As the original module is gone now and this seems to be the most promising fork will you please add this to the https://galaxy.ansible.com/ page?

**Comment by TravisWhitehead** [comment]
Hi @spech66, this role is available on Ansible Galaxy as `tag1consulting.borgbackup`. Please close this issue if it works for you.

**Comment by spech66** [comment]
Thank you @TravisWhitehead I updated my requirements file. Maybe you want to add the galaxy information to the Readme file?

**Comment by TravisWhitehead** [comment]
@spech66 How's #11 look?

**Comment by spech66** [comment]
@TravisWhitehead Perfect! Thank you so much!
